import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_application_1/model/user.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppService {
  static SharedPreferences? prefs;
  static List<String>? categories = [
    '.NET Framework',
    '3D',
    'ActionScript ',
    'Active Directory ',
    'Administration',
    'Agile ',
    'Ajax',
    'Amazon Kindle Fire',
    'Analytics',
    'Android',
    'Angular',
    'AngularJS',
    'Ansible',
    'Apache',
    'Apache Camel',
    'Apache Cassandra',
    'Apache Kafka',
    'Apache Spark',
    'API',
    'App Store',
    'Arduino',
    'ASP',
    'ASP.NET',
    'Audio',
    'AutoCAD',
    'AWS',
    'Backbone',
    'bash',
    'Basic',
    'Big Data',
    'Bitcoin',
    'Blockchain',
    'Bootstrap',
    'BSD',
    'Business',
    'C#',
    'C++',
    'Cisco',
    'Citrix',
    'Clojure',
    'Cloud',
    'Cocoa',
    'Cocos2D',
    'CouchDB',
    'CSS',
    'CSS3',
    'Cucumber',
    'Dart ',
    'Database',
    'Delphi',
    'Design',
    'Django',
    'Docker',
    'Dojo ',
    'DOM',
    'Drupal',
    'Eclipse',
    'EJB',
    'Erlang',
    'Ethereum',
    'F#',
    'Facebook',
    'Fedora',
    'Firebug',
    'Flash ',
    'Flex',
    'Fonts',
    'For Dummies',
    'Framework',
    'FreeBSD',
    'Games Development',
    'GIMP',
    'GIS',
    'Git',
    'Google',
    'Grails Framework ',
    'Graph',
    'Groovy',
    'Hack ',
    'Hacking',
    'Hadoop',
    'Haskell',
    'HeadFirst',
    'Hibernate',
    'Hive',
    'HTML',
    'HTML5',
    'Hyper-V',
    'IaaS',
    'IBM',
    'IDE',
    'IIS',
    'In Action',
    'InDesign',
    'iOS',
    'iPad',
    'iPhone',
    'Java',
    'JavaFX',
    'JavaScript',
    'JIRA',
    'Joomla',
    'jQuery',
    'JSON',
    'Juniper',
    'Knockout ',
    'Kubernetes',
    'LEGO',
    'Linux',
    'Lisp',
    'Lua',
    'Mac',
    'Machine Learning',
    'MapReduce',
    'MariaDB',
    'MATLAB',
    'Media',
    'Microsoft',
    'Microsoft Access',
    'Microsoft Azure',
    'Microsoft Excel ',
    'Microsoft Office ',
    'Microsoft Word',
    'Mobile',
    'MongoDB',
    'Munin ',
    'MVC',
    'MySQL',
    'Nagios',
    'NetBeans',
    'Network',
    'Neural Networks',
    'Node',
    'Node.js',
    'NoSQL',
    'NumPy',
    'Nutshell',
    'Objective-C',
    'OpenBSD',
    'OpenGL',
    'Optimization',
    'Oracle',
    'Outlook',
    'PaaS',
    'Panda3D',
    'Patterns',
    'Perl',
    'Phone Development',
    'PhoneGap',
    'Photoshop ',
    'PHP',
    'PlayStation',
    'PostgreSQL',
    'PowerShell',
    'Programming',
    'Project',
    'Python',
    'Rails',
    'Raspberry Pi',
    'Redmine',
    'Regular Expressions',
    'Ruby',
    'Rust',
    'Sams Teach Yourself',
    'SAP',
    'Sass',
    'Scala',
    'SDK',
    'Security',
    'SEO',
    'Server',
    'SharePoint',
    'Shell',
    'Silverlight',
    'SOA',
    'SOAP',
    'Software',
    'Solaris',
    'Sphinx',
    'Splunk',
    'Spring',
    'SQL',
    'Subversion',
    'TensorFlow',
    'Testing ',
    'Titanium',
    'Training Kit',
    'Tuning',
    'Twitter',
    'Ubuntu ',
    'UML',
    'Unity',
    'VB',
    'VBA',
    'Visual Basic',
    'Visual Studio',
    'Visualization',
    'VMM',
    'WebGL',
    'WebSocket',
    'Wi-Fi',
    'Wii',
    'Windows',
    'WordPress',
    'WPF',
    'XAML',
    'Xbox',
    'Xcode',
    'XML',
    'Yahoo'
  ];
  static User? get user {
    if (prefs?.getString('user') != null) {
      var data = jsonDecode(prefs?.getString('user') ?? '');
      return User.fromJson(data, data['token']);
    } else {
      return null;
    }
  }

  static void setUser(User user) {
    prefs?.setString('user', jsonEncode(user.toJson()));
  }

  static void init() async {
    WidgetsFlutterBinding.ensureInitialized();
    prefs = await SharedPreferences.getInstance();
  }
}
